tEventService:                          # service name
  endpoint: http://localhost:8081/event # direct endpoint
  ribbon:                               # manually ribbon
    listOfServers: localhost:8081
  path: /service                        # general path
  connectTimeout: 1000                  # default=1000
  readTimeout: 10000                    # default=30000

thrift.client.max.threads: 10           # default=8